name: Build-Push Image
description: Builds the bootstrapper image
inputs:
  platform:
    description: The platform for which the image will be built
    required: true
  labels:
    description: The labels for the built image
    required: true
  image-tag:
    description: The tag of the built image
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Golang
      uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
      with:
        go-version-file: "${{ github.workspace }}/go.mod"
    - name: Prepare build parameters
      id: prep
      shell: bash
      run: |
        hack/build/ci/prepare-build-variables.sh
    - name: Build target
      uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
      with:
        oci: true
        containerfiles: |
         ./Dockerfile
        platforms: linux/${{ inputs.platform }}
        tags: bootstrapper-${{ inputs.platform }}:${{ inputs.image-tag }}
        labels: ${{ inputs.labels }}

